import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full bg-[#1a1b26] min-h-screen antialiased overflow-hidden">
          <div className="container mx-auto px-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
